### ISSUE TITLE
company-css does not support complete in multi-lines CSS

### ISSUE THREAD

**Issue by stardiviner** [company-mode/company-mode#1029]
For example, I have CSS code like this:
```css
div {
  transform:
    perspective(75em) rotateX(18deg);
  box-shadow:
    rgba(22, 31, 39, 0.42) 0px 60px 123px -25px,
    rgba(19, 26, 32, 0.08) 0px 35px 75px -35px;
  border-radius: 10px;
  border: 1px solid;
  border-color:
    rgb(213, 220, 226)
    rgb(213, 220, 226)
    rgb(184, 194, 204);
}
```
Below the `transform:` line, I type `perspe` does not get completions. I have to type behind and on `transform:` line like this: `transform: perspe|`.
